[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[env]
  REACT_APP_FIREBASE_API_KEY = "AIzaSyBR0bk7xUxHwKYA0l8QYOSzNp2xkZL_VmY"
  REACT_APP_FIREBASE_AUTH_DOMAIN = "albabeautysettersystem.firebaseapp.com"
  REACT_APP_FIREBASE_PROJECT_ID = "albabeautysettersystem"
  REACT_APP_FIREBASE_STORAGE_BUCKET = "albabeautyssettersystem.firebasestorage.app"
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "830149463357"
  REACT_APP_FIREBASE_APP_ID = "1:830149463357:web:09258a6fb92847b7d20954"
  REACT_APP_FIREBASE_MEASUREMENT_ID = "G-SJQWD0GQ0Q"
